# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007d7558d1e3bf52a47e01e05554e1b97888e4571030ee1b37bcd5fff842f204a306ea94170dff939f2f14b8f60665d71058e93fc818d48968f8eda34b2248b5

test:
  secret_key_base: 14addb298e518181cd2484c3025bd7264f31c0cb058416e3b8c9ad6790a75d1d9a1baf785eb11cbaa0fcab1ae6467893dd029d5410f65b461bc1734b109704ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
